#!/usr/bin/bash
echo "Starting npm install of jest"
npm install --save-dev jest
echo "Finished npm install of jest"

echo "Starting npm install of babel-jest, @babel/core, and @babel/preset-env"
npm install --save-dev babel-jest @babel/core @babel/preset-env
echo "Finished npm install of babel-jest, @babel/core, and @babel/preset-env"

echo "Starting npm install of eslint"
npm install --save-dev eslint
echo "Finished npm install of eslint"

echo '{
  "scripts": {
    "lint": "./node_modules/.bin/eslint",
    "check-lint": "lint [0-9]*.js",
    "dev": "npx babel-node",
    "test": "jest",
    "full-test": "./node_modules/.bin/eslint [0-9]*.js && jest"
  },
  "devDependencies": {
    "@babel/core": "^7.6.0",
    "@babel/preset-env": "^7.6.0",
    "@babel/node": "^7.8.0",
    "eslint": "^6.4.0",
    "eslint-config-airbnb-base": "^14.0.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jest": "^22.17.0",
    "jest": "^24.9.0"
  }
}' > package.json

echo "Creating package.json"

echo "module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          node: 'current',
        },
      },
    ],
  ],
};" > babel.config.js

echo "Creating babel.config.js"

echo "module.exports = {
  env: {
    browser: false,
    es6: true,
    jest: true,
  },
  extends: [
    'airbnb-base',
    'plugin:jest/all',
  ],
  globals: {
    Atomics: 'readonly',
    SharedArrayBuffer: 'readonly',
  },
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: 'module',
  },
  plugins: ['jest'],
  rules: {
    'max-classes-per-file': 'off',
    'no-underscore-dangle': 'off',
    'no-console': 'off',
    'no-shadow': 'off',
    'no-restricted-syntax': [
      'error',
      'LabeledStatement',
      'WithStatement',
    ],
  },
  overrides:[
    {
      files: ['*.js'],
      excludedFiles: 'babel.config.js',
    }
  ]
};" > .eslintrc.js

echo ".eslintrc.js file creation finished"

echo "Starting installation of dependencies"
npm install
echo "dependency installation finished"

echo "All installations finished!"
